version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: reservas-postgres
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=salasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    name: postgres-salas-data
