version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservas-api
    ports:
      - "5027:5027"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=salasdb;Username=usuario;Password=senha
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: reservas-postgres
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=salasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
    name: postgres-salas-data
